name: Dependencies (Conan)

on:
  workflow_dispatch:
  pull_request:
    branches: [ "**" ]

jobs:
  conan-install:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends git cmake python3 python3-pip pkg-config

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Conan
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade conan

      - name: Cache Conan
        uses: actions/cache@v4
        with:
          path: |
            ~/.conan2
          key: ${{ runner.os }}-conan2-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan2-

      - name: Conan install (PRESET=Release) with sudo
        env:
          PRESET: Release
        run: |
          sudo --preserve-env=HOME,PRESET -E make setup PRESET=${PRESET} | cat
          sudo chown -R "$USER":"$USER" build || true

      - name: List build folder
        run: |
          ls -la build | cat || true


